AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  stayway-media-api lambda

Parameters:
  Env:
    Type: String
    Description: Environment name

Resources:
  PersistMedia:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Env}-persist-media
      CodeUri: /tmp/bin
      Handler: stayway-media-lambda
      Runtime: go1.x
      Layers:
        - "arn:aws:lambda:ap-northeast-1:031362952436:layer:ffmpeg:1"
        - "arn:aws:lambda:ap-northeast-1:031362952436:layer:image-magick:1"
      Role: !Sub arn:aws:iam::031362952436:role/${Env}-persist-media
      MemorySize: 1024
      Environment:
        Variables:
          env: !Sub ${Env}
          action: persist_media
      Timeout: 300
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Sub "arn:aws:sqs:ap-northeast-1:031362952436:${Env}-persist-media"
            BatchSize: 1
