ALTER TABLE vlog MODIFY youtube_url VARCHAR(1024) NOT NULL COMMENT 'youtubeのURL';

ALTER TABLE user
  MODIFY url  VARCHAR(1024) DEFAULT NULL COMMENT 'ユーザーが自由に設定するURL',
  MODIFY facebook_url  VARCHAR(1024) DEFAULT NULL COMMENT 'FacebookURL',
  MODIFY instagram_url  VARCHAR(1024) DEFAULT NULL COMMENT 'InstagramURL',
  MODIFY twitter_url  VARCHAR(1024) DEFAULT NULL COMMENT 'TwitterURL';

ALTER TABLE tourist_spot MODIFY instagram_url  VARCHAR(1024) DEFAULT NULL COMMENT 'instagram';
