CREATE TABLE IF NOT EXISTS user_favorite_vlog (
  user_id BIGINT UNSIGNED NOT NULL,
  vlog_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, vlog_id),
  CONSTRAINT user_favorite_vlog_user_id FOREIGN KEY(user_id) REFERENCES user(id),
  CONSTRAINT user_favorite_vlog_vlog_id FOREIGN KEY(vlog_id) REFERENCES vlog(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT = 'ユーザーがお気に入りしたVlog';
