ALTER TABLE notice ADD deleted_at DATETIME DEFAULT NULL AFTER updated_at;
ALTER TABLE report ADD updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE report ADD deleted_at DATETIME DEFAULT NULL AFTER updated_at;