CREATE TABLE IF NOT EXISTS batch_option (
  name            TINYINT UNSIGNED NOT NULL,
  value           VARCHAR(255) NOT NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(name),
  UNIQUE INDEX batch_option(name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT = 'バッチの実行履歴kvs';
