// Code generated by go-enum
// DO NOT EDIT!

package wordpress

import (
	"fmt"
)

const (
	// CategoryTypeUndefined is a CategoryType of type Undefined
	CategoryTypeUndefined CategoryType = iota
	// CategoryTypeJapan is a CategoryType of type Japan
	CategoryTypeJapan
	// CategoryTypeWorld is a CategoryType of type World
	CategoryTypeWorld
	// CategoryTypeTheme is a CategoryType of type Theme
	CategoryTypeTheme
)

const _CategoryTypeName = "undefinedjapanworldtheme"

var _CategoryTypeMap = map[CategoryType]string{
	0: _CategoryTypeName[0:9],
	1: _CategoryTypeName[9:14],
	2: _CategoryTypeName[14:19],
	3: _CategoryTypeName[19:24],
}

// String implements the Stringer interface.
func (x CategoryType) String() string {
	if str, ok := _CategoryTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("CategoryType(%d)", x)
}

var _CategoryTypeValue = map[string]CategoryType{
	_CategoryTypeName[0:9]:   0,
	_CategoryTypeName[9:14]:  1,
	_CategoryTypeName[14:19]: 2,
	_CategoryTypeName[19:24]: 3,
}

// ParseCategoryType attempts to convert a string to a CategoryType
func ParseCategoryType(name string) (CategoryType, error) {
	if x, ok := _CategoryTypeValue[name]; ok {
		return x, nil
	}
	return CategoryType(0), fmt.Errorf("%s is not a valid CategoryType", name)
}

// MarshalText implements the text marshaller method
func (x CategoryType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *CategoryType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCategoryType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// EntityTypePost is a EntityType of type Post
	EntityTypePost EntityType = iota + 1
	// EntityTypeLocation is a EntityType of type Location
	EntityTypeLocation
	// EntityTypeMovie is a EntityType of type Movie
	EntityTypeMovie
	// EntityTypeComic is a EntityType of type Comic
	EntityTypeComic
	// EntityTypeFeature is a EntityType of type Feature
	EntityTypeFeature
	// EntityTypeCategory is a EntityType of type Category
	EntityTypeCategory
	// EntityTypeLocationCat is a EntityType of type Location__cat
	EntityTypeLocationCat
)

const _EntityTypeName = "postlocationmoviecomicfeaturecategorylocation__cat"

var _EntityTypeMap = map[EntityType]string{
	1: _EntityTypeName[0:4],
	2: _EntityTypeName[4:12],
	3: _EntityTypeName[12:17],
	4: _EntityTypeName[17:22],
	5: _EntityTypeName[22:29],
	6: _EntityTypeName[29:37],
	7: _EntityTypeName[37:50],
}

// String implements the Stringer interface.
func (x EntityType) String() string {
	if str, ok := _EntityTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("EntityType(%d)", x)
}

var _EntityTypeValue = map[string]EntityType{
	_EntityTypeName[0:4]:   1,
	_EntityTypeName[4:12]:  2,
	_EntityTypeName[12:17]: 3,
	_EntityTypeName[17:22]: 4,
	_EntityTypeName[22:29]: 5,
	_EntityTypeName[29:37]: 6,
	_EntityTypeName[37:50]: 7,
}

// ParseEntityType attempts to convert a string to a EntityType
func ParseEntityType(name string) (EntityType, error) {
	if x, ok := _EntityTypeValue[name]; ok {
		return x, nil
	}
	return EntityType(0), fmt.Errorf("%s is not a valid EntityType", name)
}

// MarshalText implements the text marshaller method
func (x EntityType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *EntityType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseEntityType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// StatusPublish is a Status of type Publish
	StatusPublish Status = iota + 1
	// StatusFuture is a Status of type Future
	StatusFuture
	// StatusDraft is a Status of type Draft
	StatusDraft
	// StatusPending is a Status of type Pending
	StatusPending
	// StatusPrivate is a Status of type Private
	StatusPrivate
)

const _StatusName = "publishfuturedraftpendingprivate"

var _StatusMap = map[Status]string{
	1: _StatusName[0:7],
	2: _StatusName[7:13],
	3: _StatusName[13:18],
	4: _StatusName[18:25],
	5: _StatusName[25:32],
}

// String implements the Stringer interface.
func (x Status) String() string {
	if str, ok := _StatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Status(%d)", x)
}

var _StatusValue = map[string]Status{
	_StatusName[0:7]:   1,
	_StatusName[7:13]:  2,
	_StatusName[13:18]: 3,
	_StatusName[18:25]: 4,
	_StatusName[25:32]: 5,
}

// ParseStatus attempts to convert a string to a Status
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid Status", name)
}

// MarshalText implements the text marshaller method
func (x Status) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
