// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/stayway-corp/stayway-media-api/pkg/adaptor/infrastructure/repository"
	"github.com/stayway-corp/stayway-media-api/pkg/application/service"
	"github.com/stayway-corp/stayway-media-api/pkg/config"
)

// Injectors from wire.go:

func InitializeScript(configFilePath config.FilePath) (*Script, error) {
	configConfig, err := config.GetConfig(configFilePath)
	if err != nil {
		return nil, err
	}
	aws := configConfig.AWS
	session, err := repository.ProvideAWSSession(configConfig)
	if err != nil {
		return nil, err
	}
	mediaQueryRepositoryImpl := &repository.MediaQueryRepositoryImpl{
		AWSConfig:  aws,
		AWSSession: session,
	}
	mediaCommandRepositoryImpl := &repository.MediaCommandRepositoryImpl{
		AWSConfig:  aws,
		AWSSession: session,
	}
	mediaCommandServiceImpl := &service.MediaCommandServiceImpl{
		AWSConfig:              aws,
		AWSSession:             session,
		MediaQueryRepository:   mediaQueryRepositoryImpl,
		MediaCommandRepository: mediaCommandRepositoryImpl,
	}
	db, err := repository.ProvideDB(configConfig)
	if err != nil {
		return nil, err
	}
	script := &Script{
		MediaCommandService: mediaCommandServiceImpl,
		AWSSession:          session,
		DB:                  db,
	}
	return script, nil
}
