// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/stayway-corp/stayway-media-api/pkg/adaptor/infrastructure/repository"
	"github.com/stayway-corp/stayway-media-api/pkg/adaptor/infrastructure/repository/payjp"
	"github.com/stayway-corp/stayway-media-api/pkg/config"
)

// Injectors from wire.go:

func InitializeScript(path config.FilePath) (*Script, error) {
	configConfig, err := config.GetConfig(path)
	if err != nil {
		return nil, err
	}
	service := repository.ProvidePayjp(configConfig)
	db, err := repository.ProvideDB(configConfig)
	if err != nil {
		return nil, err
	}
	customerCommandRepositoryImpl := &payjp.CustomerCommandRepositoryImpl{
		PayjpClient: service,
	}
	script := &Script{
		PayjpClient:               service,
		DB:                        db,
		CustomerCommandRepository: customerCommandRepositoryImpl,
	}
	return script, nil
}
