// Code generated by go-enum
// DO NOT EDIT!

package serror

import (
	"fmt"
)

const (
	// CodeUndefined is a Code of type Undefined
	CodeUndefined Code = iota
	// CodeInvalidParam is a Code of type InvalidParam
	CodeInvalidParam
	// CodeNotFound is a Code of type NotFound
	CodeNotFound
)

const _CodeName = "UndefinedInvalidParamNotFound"

var _CodeMap = map[Code]string{
	0: _CodeName[0:9],
	1: _CodeName[9:21],
	2: _CodeName[21:29],
}

// String implements the Stringer interface.
func (x Code) String() string {
	if str, ok := _CodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Code(%d)", x)
}

var _CodeValue = map[string]Code{
	_CodeName[0:9]:   0,
	_CodeName[9:21]:  1,
	_CodeName[21:29]: 2,
}

// ParseCode attempts to convert a string to a Code
func ParseCode(name string) (Code, error) {
	if x, ok := _CodeValue[name]; ok {
		return x, nil
	}
	return Code(0), fmt.Errorf("%s is not a valid Code", name)
}

// MarshalText implements the text marshaller method
func (x Code) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *Code) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
